name: Publish to GitHub Packages

on:
  push:
    branches:
      - master

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  USERNAME: ${{ github.actor }}
  TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Using Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build and publish to GitHub Packages
        run: |
          ./gradlew build
          ./gradlew publish -PmavenUsername=${{ github.actor }} -PmavenPassword=${{ secrets.GITHUB_TOKEN }}

      - name: Fetch tags
        run: git fetch --tags

      - name: Get latest tag
        id: latest-tag
        run: |
          latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1))
          if [ -z "$latest_tag" ]; then
            latest_tag="v0.0.1"
            git tag "$latest_tag"
            git push --tags
          fi
          echo "::set-output name=latest_tag::$latest_tag"

      - name: Create GitHub release
        uses: actions/create-release@v1
        if: github.event_name == 'workflow_dispatch' || github.event_name == 'push' && contains(github.ref, 'tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.latest-tag.outputs.latest_tag }}
          release_name: Release ${{ steps.latest-tag.outputs.latest_tag }}
          draft: false
          prerelease: false
